name: Deploy

on:
  push:
    branches:
      - master
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set target directory
        id: set-dir
        run: |
          case "${{ github.ref_name }}" in
            master)
              echo "target_dir=/home/jena/domains/amplifiedexpansion.com/public_html" >> $GITHUB_OUTPUT
              ;;
            staging)
              echo "target_dir=/home/jena/domains/staging.amplifiedexpansion.com/public_html" >> $GITHUB_OUTPUT
              ;;
          esac
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd ${{ steps.set-dir.outputs.target_dir }}
            git fetch origin
            git reset --hard origin/${{ github.ref_name }}
